apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.name" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.deployment.env  }}  
  {{ $key }}: {{ $value | quote }}
{{- end }}
