apiVersion: v1
kind: Service
metadata:
  name: {{ include "template.name" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "template.selectorLabels" . | nindent 6 }}
  ports:
    {{- range $key, $values := .Values.service.ports  }}  
      - name: {{ $key }}
        protocol: {{ $values.protocol }}
        port: {{ $values.port }}
        targetPort: {{ $values.targetPort }}
    {{- end }}
